#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: pos
    username: pos
    password: '$6$bWSGmrw2Cpw.vmnt$H44c0ApKcmc81MWR5M1BX0bo6sObJHk84mf2r/EZuuVwj5MlKHl9dwM2NOP7MZSWtdR6yDhmmcx7UIEKf01dK.'
  packages:
    - docker.io
    - git
    - curl
    - unzip
    - nodejs
    - npm
    - openssh-server
    - net-tools
  late-commands:
    # Install docker-compose
    - curtin in-target -- apt-get install -y docker-compose
    
    # Enable Docker at boot
    - curtin in-target -- systemctl enable docker
    
    # Create project directories under /home
    - curtin in-target -- mkdir -p /home/frontend
    - curtin in-target -- mkdir -p /home/backend

    # Copy frontend and backend from ISO
    - curtin in-target -- cp -r /cdrom/custom-configs/frontend/* /home/frontend/
    - curtin in-target -- cp -r /cdrom/custom-configs/backend/* /home/backend/

    # Copy env files with existence checks
    - curtin in-target -- bash -c "[ -f /cdrom/custom-configs/frontend.env ] && cp /cdrom/custom-configs/frontend.env /home/frontend/.env || echo 'Frontend .env not found'"
    - curtin in-target -- bash -c "[ -f /cdrom/custom-configs/backend.env ] && cp /cdrom/custom-configs/backend.env /home/backend/.env || echo 'Backend .env not found'"

    # CRITICAL: Fix ownership FIRST before any operations
    - curtin in-target -- chown -R pos:pos /home/frontend /home/backend

    # Add pos user to docker group
    - curtin in-target -- usermod -aG docker pos

    # Start backend container as pos user
    - curtin in-target -- chmod +x /home/backend/entrypoint.sh
    - curtin in-target -- sudo -u pos bash -c "cd /home/backend && ./entrypoint.sh"

    # Setup Node.js and frontend as pos user
    - |
      curtin in-target -- sudo -u pos bash -c '
      # Color definitions
      CYAN="\033[0;36m"
      GREEN="\033[0;32m"
      NC="\033[0m"

      # Function to get server IP
      get_server_ip() {
        hostname -I | awk "{print \$1}"
      }

      # Function to check if command exists
      command_exists() {
        command -v "$1" >/dev/null 2>&1
      }

      echo -e "${CYAN}Setting up frontend application as pos user...${NC}"

      # Get server IP
      SERVER_IP=$(get_server_ip)

      # Install Node.js 22.x if needed (as root, then switch back)
      if ! command_exists node || ! node -v | grep -q "v2[0-9]"; then
        echo -e "${CYAN}Installing Node.js 22.x...${NC}"
        sudo apt-get update
        curl -fsSL https://deb.nodesource.com/setup_22.x | sudo bash -
        sudo apt-get install -y nodejs
        echo -e "${GREEN}Node.js installed successfully!${NC}"
        node -v
      else
        echo -e "${GREEN}Node.js already installed: $(node -v)${NC}"
      fi

      # Install global dependencies as pos user
      echo -e "${CYAN}Installing PNPM and PM2 dependencies...${NC}"
      npm install -g pm2 pnpm
      echo -e "${GREEN}PNPM and PM2 Dependencies installed globally!${NC}"

      # Set PM2_HOME for pos user
      export PM2_HOME=/home/pos/.pm2
      mkdir -p $PM2_HOME

      # Check pm2 list
      echo -e "${CYAN}Checking PM2 list...${NC}"
      pm2 list
      echo -e "${GREEN}PM2 list checked successfully!${NC}"

      # Stop existing application if running
      if pm2 id sixthkendra >/dev/null 2>&1; then
        echo -e "${GREEN}Stopping existing application...${NC}"
        pm2 delete sixthkendra
      fi

      # Change to frontend directory
      cd /home/frontend

      # Install the application dependencies
      echo -e "${CYAN}Installing application dependencies...${NC}"
      pnpm install
      echo -e "${GREEN}Application dependencies installed successfully!${NC}"

      # Build the application
      echo -e "${CYAN}Building the application...${NC}"
      pnpm build
      echo -e "${GREEN}Application built successfully!${NC}"

      # Start the application
      echo -e "${CYAN}Starting the application...${NC}"
      pm2 start pnpm --name "sixthkendra" -- run start

      # Save PM2 config
      echo -e "${CYAN}Saving PM2 config...${NC}"
      pm2 save
      echo -e "${GREEN}PM2 config saved successfully!${NC}"

      # Display results
      echo -e "\n${GREEN}Application Services:${NC}"
      echo -e " - Frontend: http://${SERVER_IP}:3000"
      echo -e " - PM2 Status:"
      pm2 list
      '

    # Setup PM2 startup as pos user
    - curtin in-target -- sudo -u pos bash -c "pm2 startup | grep 'sudo env' | bash"

    # Backend container setup and database operations (wait for backend to be ready)
    - |
      curtin in-target -- sudo -u pos bash -c '
      echo "Waiting for backend container to be ready...";
      # Wait for backend container to be running
      for i in {1..30}; do
        if docker ps --filter "name=backend" --filter "status=running" | grep -q backend; then
          echo "Backend container is up!";
          cd /home/backend
          # Execute the cache clearing commands inside the container
          echo "Clearing application cache...";
          timeout 120 docker-compose -f docker-compose-local.yml exec -T backend bash -c "php artisan optimize:clear && php artisan config:clear && php artisan config:cache" || echo "Cache clear failed, continuing...";
          # Restart the containers
          echo "Restarting containers...";
          docker-compose -f docker-compose-local.yml down && docker-compose -f docker-compose-local.yml up -d;
          # Wait for container to come back up
          echo "Waiting for container to restart...";
          sleep 15;
          # Run migrations and seed
          echo "Running migrations and seeding database...";
          timeout 300 docker-compose -f docker-compose-local.yml exec -T backend php artisan migrate:fresh --seed || echo "Database seeding failed";
          echo "Database setup completed!";
          exit 0;
        else
          echo "Backend not ready yet... retrying ($i/30)";
          sleep 10;
        fi
      done
      echo "Backend failed to start in time, skipping DB operations.";
      exit 0;
      '

    # Create systemd service for PM2
    - |
      curtin in-target -- bash -c '
      cat > /etc/systemd/system/pm2-pos.service << EOF
      [Unit]
      Description=PM2 process manager for pos user
      Documentation=https://pm2.keymetrics.io/
      After=network.target docker.service

      [Service]
      Type=forking
      User=pos
      LimitNOFILE=infinity
      LimitNPROC=infinity
      LimitCORE=infinity
      Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/pos/.npm-global/bin
      Environment=PM2_HOME=/home/pos/.pm2
      PIDFile=/home/pos/.pm2/pm2.pid
      Restart=on-failure
      WorkingDirectory=/home/pos

      ExecStart=/usr/bin/pm2 resurrect
      ExecReload=/usr/bin/pm2 reload all
      ExecStop=/usr/bin/pm2 kill

      [Install]
      WantedBy=multi-user.target
      EOF
      systemctl enable pm2-pos.service
      '